### ISSUE TITLE
Wrong translation license

### ISSUE THREAD

**Issue by comradekingu** [grommunio/grommunio-web#2]
@grammmike 
https://hosted.weblate.org/projects/grommunio/grommunio-web/#information is AGPLv3-only, when it should be
AGPLv3+, like
https://github.com/grommunio/grommunio-web/blob/b412283b8e5a40dc75f036c3062e8437e7807e79/client/zarafa/ABOUT.js

**Comment by grammmike** [comment]
@comradekingu : 👍🏻 License has been updated correctly.
