### ISSUE TITLE
Search broken

### ISSUE THREAD

**Issue by amaccuish** [grommunio/grommunio-web#20]
Can't currently search from grommunio web

> 
> PHP message: PHP Fatal error:  Uncaught Error: Call to a member function fetchArray() on bool in /usr/share/grommunio-web/server/includes/core/class.indexsqlite.php:46
> Stack trace:
> #0 /usr/share/grommunio-web/server/includes/core/class.indexsqlite.php(173): IndexSqlite->try_insert_content()
> #1 /usr/share/grommunio-web/server/includes/modules/class.advancedsearchlistmodule.php(386): IndexSqlite->search()
> #2 /usr/share/grommunio-web/server/includes/modules/class.advancedsearchlistmodule.php(54): AdvancedSearchListModule->search()
> #3 /usr/share/grommunio-web/server/includes/core/class.jsonrequest.php(59): AdvancedSearchListModule->execute()
> #4 /usr/share/grommunio-web/grommunio.php(147): JSONRequest->execute()
> #5 {main}
>   thrown in /usr/share/grommunio-web/server/includes/core/class.indexsqlite.php on line 46" while

adding error logging to class.indexsqlite.php just after the SELECT on line 45 returns "no such column: entryid".

> grommunio-index                         1.2.1.g6b167a2                lp156.88.1
> grommunio-web                           3.9.218.g5d79b59a             lp156.170.1

I have already cleared the index folders and reran the indexer.

> sqlite> .schema messages
CREATE VIRTUAL TABLE messages USING fts5 ( sender, sending, recipients, subject, content, attachments, others, tokenize ='unicode61', prefix='3 5 7', content='', contentless_delete=1)
/* messages(sender,sending,recipients,subject,content,attachments,"others") */;

**Comment by amaccuish** [comment]
fixed in 716c4f0
thanks @gromandreas

**Comment by gromandreas** [comment]
@amaccuish I just wanted to add that unfortunately it's necessary to rebuild the index, so that the search in grommunio-web returns the expected results.
