### ISSUE TITLE
PHP and Node

### ISSUE THREAD

**Issue by sm2x** [grommunio/grommunio-web#3]
What version of PHP and Node is officially supported on Grommunio version 2021.08

**Comment by jengelh** [comment]
The 2021.08.x Appliance images are based on SLE15 and inherit from it; this would be php7 and nodejs14.

**Comment by sm2x** [comment]
> The 2021.08.x Appliance images are based on SLE15 and inherit from it; this would be php7 and nodejs14.

how about the upcoming Debian/Ubuntu-based install?  if PHP is based on php7, which PHP 7.x

**Comment by jengelh** [comment]
Rule of thumb: The most recent that is available. For Ubuntu 22.04 that would be 8.0.x.

**Comment by sm2x** [comment]
Ok, thanks I have tried the latest available on repo (download.grommunio.com) yesterday, both Debian and Ubuntu seem to be incomplete yet.
