### ISSUE TITLE
Collapsing en_GB into en_US screws up dates

### ISSUE THREAD

**Issue by P-Blackburn** [grommunio/grommunio-web#5]
Seems there was a commit to collapse en_GB and en_US along with a comment that Grommunio does not distinguish between the two.

The problem here which may not be immediately apparent to unsere deutschen Freunde :) is that our US cousins order dates in a completely alien way and out of step with the rest of the English speaking world, and world in general.  The en_US locale displays dates month/day/year .... the rest of humanity typically orders dates day/month/year.

Please put an `en_GB` locale and possibly an `en_EN` locale under language in `/usr/share/grommunio-web/server/language/` to address this issue.

The date formatting should then sort itself out subject to the OS having the relevant en_EN, en_GB locales installed.

This will at least enable the users to configure their own locales - (however, there remains an issue with the Gromunio web admin part of the app that I have not looked into yet, where when a user account is created there is a far more limited selection of locale's to choose from.)

Peter

**Comment by P-Blackburn** [comment]
Quickly looking into admin-web  without running up the Caddy stuff (may do later) ... looks like creating a en-GB.json and en-EN.json  copying say the existing en-US.json  in the admin-web/src/i18n folder will enable administrators to create new user accounts picking up the en_GB and en_EN locales at creation time, which cannot be done at present.  If this is also attended to then dates of the form day/month/year will then effectively follow from the OS's installed locales for those locales.

Hope this helps

Peter

**Comment by jengelh** [comment]
There is no en_EN, because ISO 3166 does not specify an "EN" territory. /usr/share/grommunio-web is primarily concerned with translations, not so much number formatting (that's more a result of `setlocale`), though there is

```
msgid "jS F Y"
msgstr "F j, Y"
```

Really: The Settings dialog has a fixed dropdown list whereas technically it should be a combobox allowing arbitrary locale strings, just like it's possible to freely set LC_* in a Unix shell.

**Comment by P-Blackburn** [comment]
(Understood with no EN territory etc its just a short hand for the rest of the English speaking world.)  A combobox permitting arbitrary strings may work to include the rest of the English speaking world, but at present forcing the only English as  "en_US"  most certainly negatively impacts the date formatting for none Americans.

**Comment by jengelh** [comment]
You are probably referring to commit 20f9d18c4205f6f01ef0bba2339afc22864c71f3 . However, we never seemed to have _had_ en_GB definitions (a directory `server/language/en_GB.UTF-8/`) to begin with. So what you believed to be "English (British)" would have still used US date formatting as far as I can tell. Anyway, if you could share the British date foramtting, we can add it.

**Comment by P-Blackburn** [comment]
This article might help [https://iso.mit.edu/americanisms/date-format-in-the-united-states/](https://iso.mit.edu/americanisms/date-format-in-the-united-states/)     Essentially Americans are unique in the world formatting numerical dates from left to right   Month -> Day -> Year.     The rest of the English speaking world use an order from left to right of Day -> Month -> Year.

So today would be represented "17/12/22"  in the UK (similarly "17.12.22" in Germany and Europe).  However, in the US today will be "12/17/22"....

**Comment by grammmike** [comment]
see https://github.com/grommunio/grommunio-web/commit/ed8eacc5ec0c1a5be7bda4f80080808d4b6829c2 - example:
en_US
![image](https://user-images.githubusercontent.com/79457834/210115511-66a62ee4-ffec-4255-98b9-a6a7acf4622b.png)
vs.
en_GB
![image](https://user-images.githubusercontent.com/79457834/210115623-3ea4eb1f-ed08-423a-9a78-915383f4854e.png)
